# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 856601aeb09423d0992dd699325c289eea7f0eb1091e87fc0100a548859bb4be49312a29cf3d41011f5c787f308a045533d42f50f4b80ed1f66f4c3c6a85dbf3

test:
  secret_key_base: 8c577db896eb9dd3171e8144a3045fc1cc9f9b8531d195bb4d44c96d4ab8ac34a9320f4277f5c9267416275217cf9dac5cb5b8e9ec81b2c7e2ad1cbd1df03e06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mailgun_password: yesipapi1
